[package]
name = "tinycnn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
mnist = "0.4.1"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
crossbeam = "0.8.2"
